let pizzaJson = [
  {
    id: 1,
    name: "Mussarela",
    img: "images/pizza.png",
    price: 20.19,
    sizes: ["100g", "530g", "860g"],
    description: "Uma deliciosa pizza de Mussarela, com queijo derretido, molho de tomate fresco e temperos selecionados.",
  },
  {
    id: 2,
    name: "Calabresa",
    img: "images/pizza2.png",
    price: 18.0,
    sizes: ["320g", "530g", "860g"],
    description: "A clássica pizza de Calabresa, com fatias generosas de linguiça calabresa, cebola, e queijo derretido sobre um delicioso molho de tomate.",
  },
  {
    id: 3,
    name: "Quatro Queijos",
    img: "images/pizza3.png",
    price: 17.45,
    sizes: ["320g", "530g", "860g"],
    description: "A tradicional pizza de Quatro Queijos, com uma mistura irresistível de queijos muçarela, parmesão, gorgonzola e catupiry sobre uma massa crocante.",
  },
  {
    id: 4,
    name: "Americana",
    img: "images/pizza4.png",
    price: 19.77,
    sizes: ["320g", "530g", "860g"],
    description: "A saborosa pizza à moda Americana, com pepperoni, pimentão, cebola e uma generosa camada de queijo derretido, perfeita para os amantes de sabores intensos.",
  },
  {
    id: 5,
    name: "Sorvete",
    img: "images/pizza5.png",
    price: 21.43,
    sizes: ["320g", "530g", "860g"],
    description: "Uma pizza inusitada e deliciosa, feita com uma massa doce e crocante, coberta com sorvete cremoso e uma variedade de coberturas saborosas, perfeita para sobremesa!",
  },
  {
    id: 6,
    name: "Moda da Casa",
    img: "images/pizza6.png",
    price: 18.55,
    sizes: ["320g", "530g", "860g"],
    description: "A pizza Moda da Casa é uma criação exclusiva da nossa pizzaria, com ingredientes selecionados e um sabor único que você só encontra aqui!",
  },
  {
    id: 7,
    name: "Chocolate",
    img: "images/pizza7.png",
    price: 22.36,
    sizes: ["320g", "530g", "860g"],
    description: "Uma pizza doce e irresistível, coberta com chocolate derretido, frutas frescas e uma generosa camada de chantilly, perfeita para os amantes de sobremesas!",
  },
];
